#lang racket/gui

(define (run-calc)
  (define calc-frame%
    (class frame%
      (super-new)
      (define (on-size w h)
        (right-align w))
      (override on-size)))
  (define mainwin (new calc-frame% [label "Racket Calculator | Basic"]))
  (define num-display (new text-field% [parent mainwin]
                                       [label ""]
                                       [init-value "0"]
                                       [enabled #f]))
  (define (right-align w)
    (let ((ed (send num-display get-editor)))
      (send ed set-max-width (- w 16))
      (send ed set-paragraph-alignment 0 'right)))
  (define button-area (new horizontal-panel% [parent mainwin]))
  (define column1 (new vertical-panel% [parent button-area]))
  (define column2 (new vertical-panel% [parent button-area]))
  (define column3 (new vertical-panel% [parent button-area]))
  (define column4 (new vertical-panel% [parent button-area]))
  (define button-m+ (new button% [parent column1] [label "M+"]))
  (define button-m- (new button% [parent column2] [label "M-"]))
  (define button-mc (new button% [parent column3] [label "MC"]))
  (define button-mr (new button% [parent column4] [label "MR"]))
  (define button-<- (new button% [parent column1] [label "<-"]))
  (define spacer (new panel% [parent column2]))
  (define button-ce (new button% [parent column3] [label "CE"]))
  (define button-ac (new button% [parent column4] [label "AC"]))
  (define button-lp (new button% [parent column1] [label "("]))
  (define button-rp (new button% [parent column2] [label ")"]))
  (define button-rc (new button% [parent column3] [label "1/x"]))
  (define button-% (new button% [parent column4] [label "%"]))
  (define button-+- (new button% [parent column1] [label "+-"]))
  (define button-sq (new button% [parent column2] [label "^2"]))
  (define button-sr (new button% [parent column3] [label "sqrt"]))
  (define button-fn (new button% [parent column4] [label "f()"]))
  (define button-7 (new button% [parent column1] [label "7"]))
  (define button-8 (new button% [parent column2] [label "8"]))
  (define button-9 (new button% [parent column3] [label "9"]))
  (define button-/ (new button% [parent column4] [label "/"]))
  (define button-4 (new button% [parent column1] [label "4"]))
  (define button-5 (new button% [parent column2] [label "5"]))
  (define button-6 (new button% [parent column3] [label "6"]))
  (define button-* (new button% [parent column4] [label "*"]))
  (define button-1 (new button% [parent column1] [label "1"]))
  (define button-2 (new button% [parent column2] [label "2"]))
  (define button-3 (new button% [parent column3] [label "3"]))
  (define button-- (new button% [parent column4] [label "-"]))
  (define button-0 (new button% [parent column1] [label "0"]))
  (define button-pt (new button% [parent column2] [label "."]))
  (define button-= (new button% [parent column3] [label "="]))
  (define button-+ (new button% [parent column4] [label "+"]))
  (send mainwin show #t)
  (right-align (- (send mainwin get-width) 4)))
